### ISSUE TITLE
Is it possible to send a message to a channel without an event?

### ISSUE THREAD

**Issue by lluiscab** [teamreflex/DiscordPHP#132]
I'm developing a bot and my idea is to run it every hour or so. Using the youtube api I want to check if there's new videos on a channel (Arleady done) the problem is: How can I send a message to a channel without $message->reply(); ? I've been looking for a docs but I couldn't find anything. Any help? ;)

**Comment by uniquoooo** [comment]
```php
$guild = $discord->guilds->get('id', 'guild id');
$channel = $guild->channels->get('id', 'channel id');

$channel->sendMessage('my message here');
```

**Comment by lluiscab** [comment]
How can I get the id and the guild id of the first line? Also, what's the id at the second line?

**Comment by uniquoooo** [comment]
Replace `channel id` with the ID of the channel you want to send the message to and replace `guild id` with the guild the channel is in. You can get both of those by enabling developer mode in the client by going to `User Settings -> Appearance -> Enable Developer Mode` and right clicking on the guild and channel you want.

**Comment by lluiscab** [comment]
And the two 'id' set as the first parameter of the functions? Do I leave they? Like when you use true or false on a fucntion? I mean, do I have to change them?

**Comment by uniquoooo** [comment]
Yeah, leave the `id` as that is the key you are looking for. If you want you could change the `id`'s to `name` and then put in the names of the guild and channel but that isn't recommended.

**Comment by lluiscab** [comment]
Okay, thanks ;)

**Comment by lluiscab** [comment]
I think I have something wrong here? Basically the message is sent three or four times and not just one
http://hastebin.com/zihicemahi.php

**Comment by Lytearro** [comment]
Yeah, you need to call an `exit()` or `die()` after sending the message so that it will only send once.

**Comment by judahnator** [comment]
Sorry to reopen something old, but I seem to be having the same issue.

I can send and receive messages with the "->on('message')" event, but cant seem to send anything from outside that.

Here is my code:
http://pastebin.com/Tz42UDQF

The only reason I am attempting to do it this way is because the factory does not seem to work either.
`$channel = $discord->factory(Channel::class, ['id' => '{{channel_id}}']);`
It returns a channel instance, but all fields except "id" are null and "->sendMessage()" does not send a message (returns promise though);

Any ideas? Am I just doing something wrong? Any debug info I should provide?
