### ISSUE TITLE
How to call bot action from http server

### ISSUE THREAD

**Issue by lefuturiste** [teamreflex/DiscordPHP#262]
I have successfully created a bot with this library, but I want to do action with this when I receive a http request.
How to include this library https://github.com/reactphp/http/ to discord bot ?
Some code examples...
Thanks for your response

**Comment by scrummerlp** [comment]
This Library is already a dependency of the Bot. It's not directly included but it's a subdependency. So to go safe you can just add it to your own composer.json by adding this to your **require** block:

```
{
    "require": {
        "react/http-client": "0.4.17"
    }
}
```

**Comment by scrummerlp** [comment]
Imagine someone calls a GET request to your bot you can just make it so that your HTTP requests are getting forwarded to one file where you handle all the requests.
Then you can read your action (what you exactly want to do) out of the request.
Then make sure that the http-client from react is loaded via autoloader and call it.

**Comment by lefuturiste** [comment]
How I can call action to the bot from other file ?

**Comment by key2peace** [comment]
@lefuturiste you mean have the bot also act as webserver? the answer is: add the support for it yourself

**Comment by lefuturiste** [comment]
so the bot can be controlled by using an HTTP api

**Comment by lefuturiste** [comment]
now this issue is useless, I find another way to do that. I think it's better to close that
