### ISSUE TITLE
Event naming inconsistency

### ISSUE THREAD

**Issue by JaxkDev** [teamreflex/DiscordPHP#433]
In the documentation and constants in Event you have all events in capital letters however when emitting certain events discordPHP has them in lowercase so for example
emitting 'ready'
while listening for Event::READY ('READY') will not function.

Some clearer documentation or use of the above constant(s) needed.

**Comment by key2peace** [comment]
as far as I know @davidcole1340 was planning to make them case insensitive in order to fix that

**Comment by JaxkDev** [comment]
Isnt DiscordPHP using the Evenement.EventEmitterTrait, That is already case sensitive by use of array keys.

**Comment by key2peace** [comment]
yes, the goal is to make it case INsensitive :P

**Comment by davidcole1340** [comment]
`Event::READY` is not actually the same as the `'ready'` event, so it will probably be removed. The bot isn't 'ready' until you have received all the guilds, which are sent in `GUILD_CREATE` events after the `READY` event, which is when `'ready'` is emitted.

But yes, ideally we will change it to be case insensitive in a later update, but due to `'READY' !== 'ready'` there will be breaking changes.
